// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxgb704juxjT2fLIQ03F76j6hWxcElR7g',
    appId: '1:546096928466:android:5bfac90f7ac0892267ff0b',
    messagingSenderId: '546096928466',
    projectId: 'zilifesaver',
    databaseURL: 'https://zilifesaver-default-rtdb.firebaseio.com',
    storageBucket: 'zilifesaver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAu_UaFSuK909C6hRtRRdZk3uIbANZrTU',
    appId: '1:546096928466:ios:81a8fed7e19ad38c67ff0b',
    messagingSenderId: '546096928466',
    projectId: 'zilifesaver',
    databaseURL: 'https://zilifesaver-default-rtdb.firebaseio.com',
    storageBucket: 'zilifesaver.appspot.com',
    iosClientId: '546096928466-shirsvsmc0hvirmaoq1af48bo2ciiqqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.userSide',
  );
}
